apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-clone-deployment
  labels:
    app: reddit-clone-same
spec:
  replicas: 2
  selector:
    matchLabels:
      app: reddit-clone-same
  template:
    metadata:
      labels:
        app: reddit-clone-same
    spec:
      containers:
      - name: reddit-clone-container
        image: vaibhavkhullar55/reddit-clone-img:latest
        ports:
        - containerPort: 3000
